### ISSUE TITLE
路由跳转的时候闪现出404页面，开发环境和生产环境都这样

### ISSUE THREAD

**Issue by chenpengjun** [54sword/react-starter#4]

**Comment by 54sword** [comment]
收到，是代码逻辑的问题，之后会修复这个问题。

https://github.com/54sword/react-starter/blob/master/src/pages/posts-detail/index.js#L66
就是这里，想处理404时候，显示的内容，逻辑没写对。

**Comment by chenpengjun** [comment]
网页加载的时候，会出现css没加载出来，页面布局是乱的

**Comment by 54sword** [comment]
生产环境会将 css 文件放置到head里。

**Comment by 54sword** [comment]
404 问题已修复

**Comment by chenpengjun** [comment]
我添加个样式，刷新页面警告
Warning: Prop `className` did not match. Server: "navbar-brand active" Client: "navbar-brand style_test__13LiP active"
必须重新启动服务才生效，这个怎么解决

**Comment by 54sword** [comment]
@chenpengjun 这个现在只能是重启才行，
因为开发环境服务端的代码，不会热更新，而客户端则是热更新，因此会导致服务端渲染的结果和客户端不一致的情况，才会出现这个警告，可以不理会这个警告。

**Comment by chenpengjun** [comment]
@54sword 但是按照实际开发场景来看的话，我写个样式不能热更新或者刷新页面也看不到效果，会影响开发的效率，您是怎么处理这个问题的，谢谢

**Comment by chenpengjun** [comment]
@54sword 突然想起来node.js可以用supervisor来守护进程，我刚用supervisor来启动服务，supervisor src/server。现在可以解决这个问题了

**Comment by chenpengjun** [comment]
@54sword 又遇到个图片导入的问题，Unexpected character '�' ，图片引入提示乱码
require('../../assets/images/searchIcon.png')，目录没有问题
