### ISSUE TITLE
node ./dist/server/server.js启动问题

### ISSUE THREAD

**Issue by Mihawk-zhao** [54sword/react-starter#9]
我在本地npm run start 之后，用 node ./dist/server/server.js可以正常使用。
但我在阿里服务器上进行同样的操作，就出现了http://localhost:3001访问不了的问题

![image](https://user-images.githubusercontent.com/19793378/61024660-e31f6c80-a3e0-11e9-86bc-855cfa729e39.png)

是什么原因啊，(服务器使用的nginx，不知道是不是这个原因引起的)

感谢解答！

**Comment by 54sword** [comment]
npm run start 是启动开发环境，如果要在服务器部署，需要根据如下步骤
https://github.com/54sword/react-starter#部署到服务器

**Comment by Mihawk-zhao** [comment]
> npm run start 是启动开发环境，如果要在服务器部署，需要根据如下步骤
> [https://github.com/54sword/react-starter#部署到服务器](https://github.com/54sword/react-starter#%E9%83%A8%E7%BD%B2%E5%88%B0%E6%9C%8D%E5%8A%A1%E5%99%A8)

我运行npm run dist会出现这个错误
![image](https://user-images.githubusercontent.com/19793378/61026431-e6692700-a3e5-11e9-95cc-7e9b90ea7fd0.png)

**Comment by Mihawk-zhao** [comment]
> npm run start 是启动开发环境，如果要在服务器部署，需要根据如下步骤
> [https://github.com/54sword/react-starter#部署到服务器](https://github.com/54sword/react-starter#%E9%83%A8%E7%BD%B2%E5%88%B0%E6%9C%8D%E5%8A%A1%E5%99%A8)

我运行npm run dist会报下面这个错误，我就没用了
![image](https://user-images.githubusercontent.com/19793378/61026527-28926880-a3e6-11e9-9a7a-130b1c4f6d86.png)

**Comment by 54sword** [comment]
建议尝试解决这个问题，然后使用npm run dist打包，发布到上线环境哦。
测试环境在服务器上运行，可能会有一些未知的问题。

**Comment by Mihawk-zhao** [comment]
> 建议尝试解决这个问题，然后使用npm run dist打包，发布到上线环境哦。
> 测试环境在服务器上运行，可能会有一些未知的问题。

那个问题我解决了，后来运行npm run dist 发现如下问题，那个undefined。。我下载你的纯净代码，打包，也会是undefinded。导致页面加载不全
node: v12.4.0
npm: 6.10.0
![image](https://user-images.githubusercontent.com/19793378/61032476-1b7c7600-a3f4-11e9-9509-4c0785c80d99.png)
这是什么原因啊，，你自己用这个纯净代码，npm run dist，dist/server/index.ejs也是这样的吗

**Comment by 54sword** [comment]
抱歉，有一个配置名称有错误，刚刚修复提交了代码，你再试一试。
